### PR TITLE
King v1.2

### PR DESCRIPTION
**Pull request by climent**
Hi

I modified the PCB to use 4 cardinal points for DI and DO, so that one can select the direction of each of those. In other words: there are two 4-point crosses, one marked with DI and one with DO. On each PCB one can select the direction the Digital Input is coming from, and where the Digital Output is heading to, and solder the correct jumper to make it happen.

I reorganized the GND on the zones, so that it removes a bunch of the via holes, and cleaned the routes on the rest of the connections.

Let me know if you like this approach.

### CODE REVIEW

**Comment by JKing-B16** [comment]
I did finally teach myself enough Fusion 360 to do an initial print. You can see a rough video of the [results on YouTube](https://www.youtube.com/watch?v=_Qa1N0CDc4w&t=42s). I've made two keyboards so far. The main ErgoDox daily driver and a compact Planck style keyboard with my son. Both with 3D printed cases.

I really do like the solution you came up with and the clean traces and greater flexibility. I wish I had thought of it.

**Comment by JKing-B16** [comment]
BTW- I still have 3 sheets of PCB's good for another 3-4 keyboards if you are interested.

**Comment by climent** [comment]
I completed my dactyl with the Sarcodina PCBs (seen [here](https://photos.app.goo.gl/iW9fWbqxfEaZERzz6) and I have extras too. I just decided to mod the King v1.1 because i thought of it being a more flexible solution. I will get a batch just to verify they work, but I don't need any right now. ;)

I also want to learn Fusion 360 to make some mods to my dactyl. Time to stop playing with KiCad and start playing with Fusion, I guess.

**Comment by JKing-B16** [comment]
I have to say the one issue I found with assembling mine was the number of connections needed between boards. I had really hoped to find a solid core ribbon cable with the same pitch as standard ribbon cable. As connected the ribbon cable was by far the hardest part. But having individually addressable LED's has been fun and useful for differentiating between by custom layout, the standard DE layout, and my gaming optimized layout.

Your board definitely looks a lot cleaner on the bottom.

**Comment by climent** [comment]
For signalling layers I opted for an LED ribbon which is attached to a single D/O on the board, as seen [here](https://photos.app.goo.gl/jMwejnaW7e21z9MC7). Per key LED is not really mu cup of tea.

Also, for inter-PCB connection, I am trying to come up with a solution that might help snapping the PCBs yet they are power/signal connected to each other, perhaps with mouse bites. However that mechanism will obvs not work for dactyls.

**Comment by JKing-B16** [comment]
keyboard

I like your underglow, but I definitely like my colors. It makes it real easy to distinguish layers, and which keys are active on which layers.

**Comment by climent** [comment]
Nice!

**Review by JKing-B16 — APPROVED** [review]

**Comment by climent** [comment]
This PR is approved, but I do not have write access to merge it.

**Comment by climent** [comment]
Updated this PR to v1.3

**Pull request closed without merging**
